In [ ]:
import numpy as np


argsort gives zou the vector that if zou use it to places objects would sort yor matrix. Its particularly usefull if you want to sort a matrix of eigenvectors in the way that you sort the eigenvalues.

In [1]:

c = np.array([5,2,8,2,4])    
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24]])

i = np.argsort(c)
a = a[:,i]

In [2]:
print(i)
print(a)

[1 3 4 0 2]
[[ 1  3  4  0  2]
 [ 6  8  9  5  7]
 [11 13 14 10 12]
 [16 18 19 15 17]
 [21 23 24 20 22]]
