In [1]:
import numpy as np
import string

This script is a memento for the np.tensordot and its uses, the reason I got interested in this was:

In [2]:
# for i in range(4):
#    h2e = np.tensordot(h2e, scf_c, axes=1).transpose(3, 0, 1, 2)

Although in the following I will lookn into examples where the dimension of the first and second input objects are identical, this operation is one where the first object has 4 and the second 2 indices. 

tensordot has multiple modes in which it runs, decided by the value of axes, the only flag. The expected result of something called tensordot is the Kronecker product defines as:


$ \mathbf{A} \otimes \mathbf{B} =  
 \begin{bmatrix} a_{11} \mathbf{B} & \cdots & a_{1n}\mathbf{B} \\
             \vdots & \ddots &           \vdots \\
  a_{m1} \mathbf{B} & \cdots & a_{mn} \mathbf{B}
\end{bmatrix}, 
$

in the following an integer matrix is multiplied with a string matrix to make this oparation easily undersatndable:

In [3]:
a = np.arange(4,2*4).reshape(2,2)
b = np.array(list(string.ascii_lowercase)[0:4], dtype=object).reshape(2,2)
c = np.tensordot(a,b, axes=0)

In [4]:
#print(a,b,c)

tensordot in mode axes = 1, between 2 (1,1) tensors is just a matrix product

In [5]:
c = np.tensordot(a,b, axes=1)

In [6]:
print(a,b,c)

[[4 5]
 [6 7]] [['a' 'b']
 ['c' 'd']] [['aaaaccccc' 'bbbbddddd']
 ['aaaaaaccccccc' 'bbbbbbddddddd']]


In [7]:
a = np.arange(0,8).reshape(2,2,2)
b = np.array(list(string.ascii_lowercase)[0:8], dtype=object).reshape(2,2,2)
c = np.tensordot(a,b, axes=1)

In [8]:
print(c.shape)
print(a,b, "=\n", c)

(2, 2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] [[['a' 'b']
  ['c' 'd']]

 [['e' 'f']
  ['g' 'h']]] =
 [[[['e' 'f']
   ['g' 'h']]

  [['aaeee' 'bbfff']
   ['ccggg' 'ddhhh']]]


 [[['aaaaeeeee' 'bbbbfffff']
   ['ccccggggg' 'ddddhhhhh']]

  [['aaaaaaeeeeeee' 'bbbbbbfffffff']
   ['ccccccggggggg' 'ddddddhhhhhhh']]]]


And 3rd is the operationmode 2, called a "double product", it results in a reduction of the dimension as compared to the initial qunatities

In [9]:
a = np.arange(4,2*4).reshape(2,2)
b = np.array(list(string.ascii_lowercase)[0:4], dtype=object).reshape(2,2)
c = np.tensordot(a,b, axes=2)

In [10]:
print(c.shape)
print(a,b, "=\n", c)

()
[[4 5]
 [6 7]] [['a' 'b']
 ['c' 'd']] =
 aaaabbbbbccccccddddddd


In [11]:
a = np.arange(0,8).reshape(2,2,2)
b = np.array(list(string.ascii_lowercase)[0:8], dtype=object).reshape(2,2,2)
c = np.tensordot(a,b, axes=2)

In [12]:
print(c.shape)
print(a,b, "=\n", c)

(2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] [[['a' 'b']
  ['c' 'd']]

 [['e' 'f']
  ['g' 'h']]] =
 [['ceeggg' 'dffhhh']
 ['aaaaccccceeeeeeggggggg' 'bbbbdddddffffffhhhhhhh']]


Final example, for the sake of understanding what the initial problem was:

In [17]:
a = np.arange(1,5).reshape(2,2)
b = np.array(list(string.ascii_lowercase)[0:16], dtype=object).reshape(2,2,2,2)
c = np.tensordot(a,b, axes=1)

In [18]:
print(c.shape)
print(a,b, "=\n", c)

(2, 2, 2, 2)
[[1 2]
 [3 4]] [[[['a' 'b']
   ['c' 'd']]

  [['e' 'f']
   ['g' 'h']]]


 [[['i' 'j']
   ['k' 'l']]

  [['m' 'n']
   ['o' 'p']]]] =
 [[[['aii' 'bjj']
   ['ckk' 'dll']]

  [['emm' 'fnn']
   ['goo' 'hpp']]]


 [[['aaaiiii' 'bbbjjjj']
   ['ccckkkk' 'dddllll']]

  [['eeemmmm' 'fffnnnn']
   ['gggoooo' 'hhhpppp']]]]


So we multiply the matrix a onto the submatrix b' of tensor b and add all elements of this multiplication into a new matrix.