In [1]:
import moha
import numpy as np
from pyscf import gto, scf, fci


In [2]:
# make a M x M adjacency matrix 
M = 4
adjacency = np.ones((M,M))
print(adjacency)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#HamRG(mu: ndarray, J_eq: ndarray, connectivity: ndarray | None = None)
RG = moha.HamRG(0, 99.0, adjacency)

In [4]:
h2_RG = RG.generate_two_body_integral(dense=True)

In [5]:
# predict properties of the seniority zero h2
print(f"number of twin pairs {M}")
B=M*(M-1)//2
print(f"number of pairs of pairs {B}")

number of twin pairs 4
number of pairs of pairs 6


In [6]:
# print all seniority zero elements, i.e. elements that corespond to pairs of "twin" pairs
a=0
for i in range(0,2*M):
    for j in range(0,2*M):
        for k in range(0,2*M):
            for l in range(0,2*M):
                if h2_RG[i,j,k,l] != 0.0:
                    a+=1
                    print(i,j,k,l)
print(M, a, h2_RG.shape)

4
0 4 1 5
0 4 2 6
0 4 3 7
1 5 2 6
1 5 3 7
2 6 3 7
6 (8, 8, 8, 8)


In [7]:
# the same again coresponding to chemists notation
h2_ch = np.transpose(h2_RG, (0, 2, 1, 3))
for i in range(0,2*M):
    for j in range(0,2*M):
        for k in range(0,2*M):
            for l in range(0,2*M):
                if h2_ch[i,j,k,l] != 0.0:
                    print(i,j,k,l)

0 1 4 5
0 2 4 6
0 3 4 7
1 2 5 6
1 3 5 7
2 3 6 7
